### ISSUE TITLE
Using CRAM files instead of BAM files

### ISSUE THREAD

**Issue by mkohailan** [jandrewrfarrell/RUFUS#21]
Hi,

Is there anyway to use CRAM files instead of BAM files?

This is the code I am running:
`runRufus.sh -s Child.bam -c Dad.bam Mom.bam Sibling1.bam Sibling2.bam Sibling(etc).bam -k 25 -t 40 -r ref.fa`

Piping the output of a CRAM-to-BAM conversion tool (e.g. SAMtools view) may not be possible as I have multiple BAM files that are used in different positions of the code (i.e. 1 BAM for `-s` and multiple BAMs for `-c`)

Appreciate your help

Thanks

**Comment by jandrewrfarrell** [comment]
Yes, Rufus is designed to work with cram files. You pass them in just like a bam but you must also use the command line option -cr to pass in the reference used to make the cram files.

**Comment by mkohailan** [comment]
Thanks. I tried the latest version of RUFUS (because the -cr option was not available in the version I have from 2018). However, the run takes almost a week to finish. It used to take 5-6 hours in the old version. Any thoughts on this?
