### ISSUE TITLE
RUFUS build fails, "unrecognized command line option "-std=c++11""

### ISSUE THREAD

**Issue by jbsysadmin** [jandrewrfarrell/RUFUS#9]
Greetings. Under Centos 6.10, latest RUFUS fails to build. Error output is below. Thanks for any leads.

Building CXX object libs/CMakeFiles/aludetect_core.dir/knownAlus.cpp.o                                       [0/1837]
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
make[5]: *** [libs/CMakeFiles/aludetect_core.dir/contig.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: *** [libs/CMakeFiles/aludetect_core.dir/aluHead.cpp.o] Error 1
make[5]: *** [libs/CMakeFiles/aludetect_core.dir/polyATail.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"cc1plus: error: unrecognized command line option "-std=
c++11"

make[5]: *** [libs/CMakeFiles/aludetect_core.dir/denovo.cpp.o] Error 1
make[5]: *** [libs/CMakeFiles/aludetect_core.dir/vcfWriter.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"
make[5]: *** [libs/CMakeFiles/aludetect_core.dir/util.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"
make[5]: *** [libs/CMakeFiles/aludetect_core.dir/knownAlus.cpp.o] Error 1
make[4]: *** [libs/CMakeFiles/aludetect_core.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [externals/rufalu/src/rufalu_project-stamp/rufalu_project-build] Error 2
make[1]: *** [externals/CMakeFiles/rufalu_project.dir/all] Error 2
make: *** [all] Error 2

**Comment by standage** [comment]
Greetings! Please consult the compiler requirements in the README. This error message suggests your compiler is too old to support C++11.

**Comment by jbsysadmin** [comment]
Thank you for writing.

At compile time, I had gcc-4.9.3 in my PATH and LD_LIBRARY_PATH.
Did I need to do anything else to make that resource known to your build process under Centos 6.x?

-John

**Comment by jbsysadmin** [comment]
I progressed further; the key was including the item below, from your online doc:

cmake ../ -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++)
However, the resulting runTest.sh never generates that final VCF. Error output enclosed.



-John


Milestones of failed test:
Child.bam.generator.V2.overlap.hashcount.fastq.bam.vcf.sorted.vcf
Child.bam.generator.V2.overlap.hashcount.fastq.bam.vcf.sorted.vcf.autosome.vcf

End of error output:

/usr/local/installs/RUFUS/scripts/Overlap.sh: line 213: 49418 Done                    $samtools view ./$NameStub.overlap.hashcount.fastq.bam
     49419 Segmentation fault      (core dumped) | $RUFUSinterpret -mod $NameStub.overlap.asembly.hash.fastq.sample -mQ 8 -r $humanRef -hf $HashList -o ./$NameStub.overlap.hashcount.fastq.bam -m 1000000 $(echo $parentCRString) -sR $NameStub.overlap.asembly.hash.fastq.Ref.sample -s $NameStub.overlap.asembly.hash.fastq.sample -e ./$NameStub.ref.RepRefHash
grep: ./Child.bam.generator.V2.overlap.hashcount.fastq.bam.vcf: No such file or directory
grep: ./Child.bam.generator.V2.overlap.hashcount.fastq.bam.vcf: No such file or directory
/usr/local/installs/RUFUS/scripts/Overlap.sh: line 221: /usr/local/installs/RUFUS/bin/tabix/bgzip: No such file or directory
/usr/local/installs/RUFUS/scripts/Overlap.sh: line 222: /usr/local/installs/RUFUS/bin/tabix/tabix: No such file or directory
0.02user 0.04system 0:00.46elapsed 14%CPU (0avgtext+0avgdata 12228maxresident)k
0inputs+56outputs (0major+23200minor)pagefaults 0swaps
[1/4]  Populating reference data for Child.bam
[2/4]  Finding contigs containing known alus for Child.bam
aluDetect: /usr/local/installs/RUFUS/bin/externals/rufalu/src/rufalu_project/libs/knownAlus.cpp:124: void KnownAlus::findContigsContainingKnownAlus(): Assertion `f' failed.
./../runRufus.sh: line 700: 49435 Aborted                 (core dumped) $RufAlu $_arg_subject $_arg_subject.generator.V2.overlap.hashcount.fastq $aluList $_arg_ref $fastaHackPath $jellyfishPath $(echo $ParentFileNames)

From: Burns, W. J.
Sent: Saturday, February 16, 2019 9:19 PM
To: 'jandrewrfarrell/RUFUS' <reply@reply.github.com>; jandrewrfarrell/RUFUS <RUFUS@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [jandrewrfarrell/RUFUS] RUFUS build fails, "unrecognized command line option "-std=c++11"" (#9)

Thank you for writing.

At compile time, I had gcc-4.9.3 in my PATH and LD_LIBRARY_PATH.
Did I need to do anything else to make that resource known to your build process under Centos 6.x?

-John

**Comment by WilliamRichards2017** [comment]
Hello jbsysadmin!  Could you send a screenshot of an ls -la on the directory that you ran the RUFUS test? This may give me more insight into what's not being built.  Also did you run the ./configure command before running the cmake and make commands?

**Comment by jbsysadmin** [comment]
The steps were:

./configure.sh
cd bin
cmake ../ -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++)
make
          cd ../testRun
          bash runTest.sh

The “ls” output is enclosed.

**Comment by WilliamRichards2017** [comment]
It looks like jellyfish didn't run on the Child sample. Maybe it produced an empty file when the program wasn't successfully built. Try running the clean.sh script and re-run test. Also, the most recent developments are also on the branch 'gfix', so I would recommend checking out that branch and rebuilding for the most up to date functionality.

**Comment by jbsysadmin** [comment]
Thanks for your help! "Child.bam.generator.V2.overlap.hashcount.fastq.bam.vcf" does now exist, after I did the following:  1) Run the clean.sh  as advised 2) check my default environment for things which may conflict with the build, and strip down LD_LIBRARY_PATH. Please close.
